# Monopoly/board.py

from Monopoly.property import Property

tiles = [
    "Go",
    Property("Old Kent Road", 60, 2, "Brown"),
    "Community Chest",
    Property("Whitechapel Road", 60, 4, "Brown"),
    "Income Tax",
    Property("King's Cross Station", 200, 25, "Station"),
    Property("The Angel Islington", 100, 6, "Light Blue"),
    "Chance",
    Property("Euston Road", 100, 6, "Light Blue"),
    Property("Pentonville Road", 120, 8, "Light Blue"),
    "Jail",
    Property("Pall Mall", 140, 10, "Pink"),
    Property("Electric Company", 150, 10, "Utility"),
    Property("Whitehall", 140, 10, "Pink"),
    Property("Northumberland Avenue", 160, 12, "Pink"),
    Property("Marylebone Station", 200, 25, "Station"),
    Property("Bow Street", 180, 14, "Orange"),
    "Community Chest",
    Property("Marlborough Street", 180, 14, "Orange"),
    Property("Vine Street", 200, 16, "Orange"),
    "Free Parking",
    Property("Strand", 220, 18, "Red"),
    "Chance",
    Property("Fleet Street", 220, 18, "Red"),
    Property("Trafalgar Square", 240, 20, "Red"),
    Property("Fenchurch Street Station", 200, 25, "Station"),
    Property("Leicester Square", 260, 22, "Yellow"),
    Property("Coventry Street", 260, 22, "Yellow"),
    Property("Water Works", 150, 10, "Utility"),
    Property("Piccadilly", 280, 24, "Yellow"),
    "Go To Jail",
    Property("Regent Street", 300, 26, "Green"),
    Property("Oxford Street", 300, 26, "Green"),
    "Community Chest",
    Property("Bond Street", 320, 28, "Green"),
    Property("Liverpool Street Station", 200, 25, "Station"),
    "Chance",
    Property("Park Lane", 350, 35, "Dark Blue"),
    "Super Tax",
    Property("Mayfair", 400, 50, "Dark Blue")
]
